[shell]
program = "/bin/zsh"

# live_config_reload = true

[window]
startup_mode = "Windowed"
title = "Alacritty"
dynamic_title = true 
decorations_theme_variant = "None"
decorations = "Full"
# opacity = 0.9
blur = true

[window.dimensions]
columns = 1000
lines = 100

[font]
size = 16.0

[font.bold]
family = "Cascadia Code NF"
style = "Bold"

[font.bold_italic]
family = "Cascadia Code NF"
style = "Bold Italic"

[font.italic]
family = "Cascadia Code NF"
style = "Italic"

[font.normal]
family = "Cascadia Code NF"
style = "Regular"

[colors]
  # Default colors
  [colors.primary]
  background = "0x1d2021"
  foreground = "0xebdbb2"

  # Normal colors
  [colors.normal]
  black   = "0x1d2021"
  red     = "0xcc241d"
  green   = "0x98971a"
  yellow  = "0xd79921"
  blue    = "0x458588"
  magenta = "0xb16286"
  cyan    = "0x689d6a"
  white   = "0xa89984"

  # Bright colors
  [colors.bright]
  black   = "0x928374"
  red     = "0xfb4934"
  green   = "0xb8bb26"
  yellow  = "0xfabd2f"
  blue    = "0x83a598"
  magenta = "0xd3869b"
  cyan    = "0x8ec07c"
  white   = "0xebdbb2"

