#!/usr/bin/env bash
file=$1
w=$2
h=$3
x=$4
y=$5

if [[ "$( file -Lb --mime-type "$file")" =~ ^image ]]; then
    # doesnt work sadge
    # img2sixel -w100 -h100 "$file" < /dev/null > /dev/tty
    exit 1
fi

pistol "$file"
