#!/usr/bin/env bash

swaylock\
  -F\
  -e\
  --image ~/.config/hypr/wall.jpg\
  --show-keyboard-layout\
  --font "Cantarell"\
  --font-size 14\
  --indicator-thickness 6\
  --inside-color 00000095\
  --layout-text-color 00000095\
  --ring-color 00000095\
  --ring-clear-color 00000095\
  --ring-wrong-color 00000095\
  --separator-color 00000095\
  --ring-ver-color 00000095\
  --layout-text-color cdd6f495\
  --inside-clear-color 00000000\
  --inside-ver-color 00000000\
  --inside-wrong-color 00000000\
  --key-hl-color a6e3a195\
  --line-color 00000095\
  --line-caps-lock-color 00000095\
  --line-clear-color 00000095\
  --text-clear-color 000000\
  --text-wrong-color 000000\
  --text-ver-color 000000\
  --text-color 000000\
