#!/usr/bin/env bash

swaylock\
  -F\
  -e\
  --image ~/wallpapers/rosepine/home.png\
  --show-keyboard-layout\
  --font "JetBrainsMono Nerd Font"\
  --font-size 14\
  --indicator-thickness 6\
  --inside-color 19172499\
  --layout-text-color 19172499\
  --ring-color 19172499\
  --ring-clear-color 19172499\
  --ring-wrong-color 19172499\
  --separator-color 19172499\
  --ring-ver-color 19172499\
  --layout-text-color e0def499\
  --inside-clear-color f6c17799\
  --inside-ver-color c4a7e799\
  --inside-wrong-color eb6f9299\
  --key-hl-color 31748f99\
  --line-color 19172499\
  --line-caps-lock-color 19172499\
  --line-clear-color 19172499\
  --text-clear-color 191724\
  --text-wrong-color 191724\
  --text-ver-color 191724\
  --text-color 191724\
