[manager]
show_hidden=true

[opener]
edit = [
	{ run = 'nvim "$@"', block = true },
]
play = [
	{ run = 'mpv "$@"', orphan = true, for = "unix" },
]
view =[
	{ run = 'imv "$@"', orphan = true, for = "unix" },
]
read=[
	{ run = 'mupdf "$@"', orphan = true, for = "unix" },
]
open = [
	{ run = 'xdg-open "$@"', desc = "Open" },
]

[open]
rules = [
	{ mime = "image/*", use = "view" },
	{ mime = "application/pdf", use = "read" },
	{ mime = "text/*", use = "edit" },
]
