[shell]
program = "/bin/zsh"

[window]
startup_mode = "Windowed"
title = "Alacritty"
dynamic_title = true 
decorations_theme_variant = "None"
decorations = "Full"
#opacity = 0.2
blur = true

[window.dimensions]
columns = 1000
lines = 100

[font]
size = 16.0

[font.bold]
family = "Cascadia Mono NF"
style = "Bold"

[font.bold_italic]
family = "Cascadia Mono NF"
style = "Bold Italic"

[font.italic]
family = "Cascadia Mono NF"
style = "Italic"

[font.normal]
family = "Cascadia Mono NF"
style = "Regular"

[colors]
  # Default colors
  # [colors.primary]
  # background = "0x1d2021"
  # foreground = "0xebdbb2"
  #
  # # Normal colors
  # [colors.normal]
  # black   = "0x1d2021"
  # red     = "0xcc241d"
  # green   = "0x98971a"
  # yellow  = "0xd79921"
  # blue    = "0x458588"
  # magenta = "0xb16286"
  # cyan    = "0x689d6a"
  # white   = "0xa89984"
  #
  # # Bright colors
  # [colors.bright]
  # black   = "0x928374"
  # red     = "0xfb4934"
  # green   = "0xb8bb26"
  # yellow  = "0xfabd2f"
  # blue    = "0x83a598"
  # magenta = "0xd3869b"
  # cyan    = "0x8ec07c"
  # white   = "0xebdbb2"

# Solarized Dark
  [colors.primary]
  background = '#002b36'
  foreground = '#839496'

# Normal colors
  [colors.normal]
  black   = '#073642'
  red     = '#dc322f'
  green   = '#859900'
  yellow  = '#b58900'
  blue    = '#268bd2'
  magenta = '#d33682'
  cyan    = '#2aa198'
  white   = '#eee8d5'

# Bright colors
  [colors.bright]
  black   = '#002b36'
  red     = '#cb4b16'
  green   = '#586e75'
  yellow  = '#657b83'
  blue    = '#839496'
  magenta = '#6c71c4'
  cyan    = '#93a1a1'
  white   = '#fdf6e3'
